on: [push]
name: Integration test
jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      streamName: aws-kcl-go-sample
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: keyid
      AWS_SECRET_KEY: keysecret
    steps:
    - uses: actions/checkout@v3

    - name: Start LocalStack
      run: |
          # install LocalStack cli and awslocal
          pip install localstack awscli-local[ver1]
          # Make sure to pull the latest version of the image
          docker pull localstack/localstack
          # Start LocalStack in the background
          localstack start -d
          # Wait 30 seconds for the LocalStack container to become ready before timing out
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete" 

    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - run: go version

    - name: Building binaries
      run: |
        go build github.com/arthurbailao/aws-kcl/cmd/aws-kcl
        go build -o sample/sample github.com/arthurbailao/aws-kcl/sample

    - name: KCL Configs
      run: |
        echo "shutdownGraceMillis = 10000" >> sample/development.properties
        echo "dynamoDBEndpoint = http://localhost:4566" >> sample/development.properties
        echo "kinesisEndpoint = http://localhost:4566" >> sample/development.properties
        echo "metricsLevel = NONE" >> sample/development.properties
        echo "retrievalMode=POLLING" >> sample/development.properties

    - name: Creating Kinesis Stream
      run: awslocal kinesis create-stream --shard-count 2 --stream-name $streamName

    - name: Starting Subscriber
      run: |
        ./aws-kcl -properties sample/development.properties &
        pid=$!
        echo "subscriberPID=$pid" >> $GITHUB_ENV


    - name: Publishing messages
      run: |
        data=$(echo -n '{"message":"sample"}' | base64 -w0)
        awslocal kinesis put-record --stream-name $streamName --data $data --partition-key sharda
        awslocal kinesis put-record --stream-name $streamName --data $data --partition-key shardb

    - run: sleep 120 # TODO: should wait for processed record

    - name: Collect results
      run: |
        kill -15 $subscriberPID
        sleep 10
        tail -n3 /tmp/shardId-00000000000*
